#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <conio.h>
#include <windows.h>
#include "estilo.h"


void Color(int Background, int Text){ // Función para cambiar el color del fondo y/o pantalla

 HANDLE Console = GetStdHandle(STD_OUTPUT_HANDLE); // Tomamos la consola.

 // Para cambiar el color, se utilizan números desde el 0 hasta el 255.
 // Pero, para convertir los colores a un valor adecuado, se realiza el siguiente cálculo.
 int    New_Color= Text + (Background * 16);

 SetConsoleTextAttribute(Console, New_Color); // Guardamos los cambios en la Consola.

}


void gotoxy (int x, int y)
{
    HANDLE manipulador;
    COORD coordenadas;
    manipulador = GetStdHandle (STD_OUTPUT_HANDLE);
    coordenadas.X = x;
    coordenadas.Y = y;
    SetConsoleCursorPosition (manipulador, coordenadas);
}
void ocultarCursor()
{
    printf("\e[?25l");
}

void mostrarCursor()
{
    printf("\e[?25h");
}

void cabecera()
{
    /// cabecera

    Color(CYAN, CYAN);
    printf("_______________________________________________________________________________________________________________________\n");
    Color(CYAN, CYAN);
    printf("________");
    Color(GREEN, GREEN);
    printf("__________");
    Color(CYAN, CYAN);
    printf("_____________________________________________________________________________________________________\n");
    Color(CYAN, CYAN);
    printf("_______");
    Color(GREEN, GREEN);
    printf("____________");
    Color(CYAN, CYAN);
    printf("__");
    Color(GREEN, GREEN);
    printf("_");
    Color(CYAN, CYAN);
    printf("_________");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("____");
    Color(CYAN, CYAN);
    printf("__");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_________________________________________________________");
    Color(CYAN, CYAN);
    printf("\n______");
    Color(GREEN, GREEN);
    printf("____");
    Color(CYAN, CYAN);
    printf("______");
    Color(GREEN, GREEN);
    printf("______");
    Color(CYAN, CYAN);
    printf("_________");
    Color(BLACK, BLACK);
    printf("__");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("__");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_____________________________________________________________");
    Color(CYAN, CYAN);
    printf("\n______");
    Color(GREEN, GREEN);
    printf("__");
    Color(CYAN, CYAN);
    printf("_________");
    Color(GREEN, GREEN);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_________");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("___");
    Color(CYAN, CYAN);
    printf("___________________________________________________________");
    Color(CYAN, CYAN);
    printf("\n________________");
    Color(GREEN, GREEN);
    printf("______");
    Color(CYAN, CYAN);
    printf("_________");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_____");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_____________________________________________________________");
    Color(CYAN, CYAN);
    printf("\n___");
    Color(GREEN, GREEN);
    printf("______");
    Color(CYAN, CYAN);
    printf("______________");
    Color(GREEN, GREEN);
    printf("_");
    Color(CYAN, CYAN);
    printf("_______");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("__");
    Color(BLACK, BLACK);
    printf("__");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("____");
    Color(CYAN, CYAN);
    printf("__");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_________________________________________________________");
    Color(CYAN, CYAN);
    printf("\n____");
    Color(GREEN, GREEN);
    printf("_____");
    Color(CYAN, CYAN);
    printf("____________");
    Color(GREEN, GREEN);
    printf("___");
    Color(CYAN, CYAN);
    printf("_______________________________________________________________________________________________");
    Color(CYAN, CYAN);
    printf("\n____");
    Color(GREEN, GREEN);
    printf("_____");
    Color(CYAN, CYAN);
    printf("____________");
    Color(GREEN, GREEN);
    printf("___");
    Color(CYAN, CYAN);
    printf("____");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("____");
    Color(CYAN, CYAN);
    printf("__");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("________________________________________________");
    Color(CYAN, CYAN);
    printf("\n___");
    Color(GREEN, GREEN);
    printf("___");
    Color(CYAN, CYAN);
    printf("__");
    Color(GREEN, GREEN);
    printf("_");
    Color(CYAN, CYAN);
    printf("__________");
    Color(GREEN, GREEN);
    printf("____");
    Color(CYAN, CYAN);
    printf("_____");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_____");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_____");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("____________________________________________________");
    Color(CYAN, CYAN);
    printf("\n___");
    Color(GREEN, GREEN);
    printf("___");
    Color(CYAN, CYAN);
    printf("_______");
    Color(GREEN, GREEN);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(GREEN, GREEN);
    printf("_____");
    Color(CYAN, CYAN);
    printf("______");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("___");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("________________________________________________");
    Color(CYAN, CYAN);
    printf("\n___");
    Color(GREEN, GREEN);
    printf("___");
    Color(CYAN, CYAN);
    printf("_______");
    Color(GREEN, GREEN);
    printf("_______");
    Color(CYAN, CYAN);
    printf("________");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_________");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("___");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_____");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("________________________________________________");
    Color(CYAN, CYAN);
    printf("\n____");
    Color(GREEN, GREEN);
    printf("________");
    Color(CYAN, CYAN);
    printf("_");
    Color(GREEN, GREEN);
    printf("_____");
    Color(CYAN, CYAN);
    printf("__________");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("__");
    Color(BLACK, BLACK);
    printf("__");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("____");
    Color(CYAN, CYAN);
    printf("__");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("_");
    Color(BLACK, BLACK);
    printf("_____");
    Color(CYAN, CYAN);
    printf("________________________________________________");
    Color(CYAN, CYAN);
    printf("\n_____");
    Color(GREEN, GREEN);
    printf("_______");
    Color(CYAN, CYAN);
    printf("_");
    Color(GREEN, GREEN);
    printf("______");
    Color(CYAN, CYAN);
    printf("____________________________________________________________________________________________________");
    Color(CYAN, CYAN);
    printf("\n_______________________________________________________________________________________________________________________\n\n\n");

    Color(BLACK, WHITE);
}
